/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedApplicationsRouteImport } from './routes/_authenticated/applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPrepareRouteImport } from './routes/_authenticated/prepare'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as InternshipsIndexRouteImport } from './routes/internships.index'
import { Route as InternshipsInternshipIdRouteImport } from './routes/internships.$internshipId'
import { Route as AuthenticatedRecruiterIndexRouteImport } from './routes/_authenticated/recruiter.index'
import { Route as AuthenticatedRecruiterInternshipIdRouteImport } from './routes/_authenticated/recruiter.$internshipId'
import { Route as AuthenticatedRecruiterNewRouteImport } from './routes/_authenticated/recruiter.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedApplicationsRoute =
  AuthenticatedApplicationsRouteImport.update({
    id: '/applications',
    path: '/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrepareRoute = AuthenticatedPrepareRouteImport.update({
  id: '/prepare',
  path: '/prepare',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InternshipsIndexRoute = InternshipsIndexRouteImport.update({
  id: '/internships/',
  path: '/internships/',
  getParentRoute: () => rootRouteImport,
} as any)
const InternshipsInternshipIdRoute = InternshipsInternshipIdRouteImport.update({
  id: '/internships/$internshipId',
  path: '/internships/$internshipId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRecruiterIndexRoute =
  AuthenticatedRecruiterIndexRouteImport.update({
    id: '/recruiter/',
    path: '/recruiter/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterInternshipIdRoute =
  AuthenticatedRecruiterInternshipIdRouteImport.update({
    id: '/recruiter/$internshipId',
    path: '/recruiter/$internshipId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecruiterNewRoute =
  AuthenticatedRecruiterNewRouteImport.update({
    id: '/recruiter/new',
    path: '/recruiter/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prepare': typeof AuthenticatedPrepareRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/internships/$internshipId': typeof InternshipsInternshipIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/recruiter/$internshipId': typeof AuthenticatedRecruiterInternshipIdRoute
  '/recruiter/new': typeof AuthenticatedRecruiterNewRoute
  '/recruiter/': typeof AuthenticatedRecruiterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/applications': typeof AuthenticatedApplicationsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/prepare': typeof AuthenticatedPrepareRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/internships/$internshipId': typeof InternshipsInternshipIdRoute
  '/internships': typeof InternshipsIndexRoute
  '/recruiter/$internshipId': typeof AuthenticatedRecruiterInternshipIdRoute
  '/recruiter/new': typeof AuthenticatedRecruiterNewRoute
  '/recruiter': typeof AuthenticatedRecruiterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/applications': typeof AuthenticatedApplicationsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/prepare': typeof AuthenticatedPrepareRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/internships/$internshipId': typeof InternshipsInternshipIdRoute
  '/internships/': typeof InternshipsIndexRoute
  '/_authenticated/recruiter/$internshipId': typeof AuthenticatedRecruiterInternshipIdRoute
  '/_authenticated/recruiter/new': typeof AuthenticatedRecruiterNewRoute
  '/_authenticated/recruiter/': typeof AuthenticatedRecruiterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/onboarding'
    | '/prepare'
    | '/profile'
    | '/saved'
    | '/internships/$internshipId'
    | '/internships/'
    | '/recruiter/$internshipId'
    | '/recruiter/new'
    | '/recruiter/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/applications'
    | '/dashboard'
    | '/onboarding'
    | '/prepare'
    | '/profile'
    | '/saved'
    | '/internships/$internshipId'
    | '/internships'
    | '/recruiter/$internshipId'
    | '/recruiter/new'
    | '/recruiter'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/applications'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/prepare'
    | '/_authenticated/profile'
    | '/_authenticated/saved'
    | '/internships/$internshipId'
    | '/internships/'
    | '/_authenticated/recruiter/$internshipId'
    | '/_authenticated/recruiter/new'
    | '/_authenticated/recruiter/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InternshipsInternshipIdRoute: typeof InternshipsInternshipIdRoute
  InternshipsIndexRoute: typeof InternshipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/applications': {
      id: '/_authenticated/applications'
      path: '/applications'
      fullPath: '/applications'
      preLoaderRoute: typeof AuthenticatedApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prepare': {
      id: '/_authenticated/prepare'
      path: '/prepare'
      fullPath: '/prepare'
      preLoaderRoute: typeof AuthenticatedPrepareRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/internships/': {
      id: '/internships/'
      path: '/internships'
      fullPath: '/internships/'
      preLoaderRoute: typeof InternshipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internships/$internshipId': {
      id: '/internships/$internshipId'
      path: '/internships/$internshipId'
      fullPath: '/internships/$internshipId'
      preLoaderRoute: typeof InternshipsInternshipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/recruiter/': {
      id: '/_authenticated/recruiter/'
      path: '/recruiter'
      fullPath: '/recruiter/'
      preLoaderRoute: typeof AuthenticatedRecruiterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/$internshipId': {
      id: '/_authenticated/recruiter/$internshipId'
      path: '/recruiter/$internshipId'
      fullPath: '/recruiter/$internshipId'
      preLoaderRoute: typeof AuthenticatedRecruiterInternshipIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recruiter/new': {
      id: '/_authenticated/recruiter/new'
      path: '/recruiter/new'
      fullPath: '/recruiter/new'
      preLoaderRoute: typeof AuthenticatedRecruiterNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedApplicationsRoute: typeof AuthenticatedApplicationsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPrepareRoute: typeof AuthenticatedPrepareRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedRecruiterInternshipIdRoute: typeof AuthenticatedRecruiterInternshipIdRoute
  AuthenticatedRecruiterNewRoute: typeof AuthenticatedRecruiterNewRoute
  AuthenticatedRecruiterIndexRoute: typeof AuthenticatedRecruiterIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedApplicationsRoute: AuthenticatedApplicationsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPrepareRoute: AuthenticatedPrepareRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedRecruiterInternshipIdRoute:
    AuthenticatedRecruiterInternshipIdRoute,
  AuthenticatedRecruiterNewRoute: AuthenticatedRecruiterNewRoute,
  AuthenticatedRecruiterIndexRoute: AuthenticatedRecruiterIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InternshipsInternshipIdRoute: InternshipsInternshipIdRoute,
  InternshipsIndexRoute: InternshipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
